name: health-check

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  health-check-scheduled:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          # Check the following URLs one by one sequentially
          url: https://pokedex-2023.fly.dev/
      - name: health check fieled notification
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
            severity: info
            details: the app is works!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}