name: Deployment pipeline

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master
  pull_request:
    branches: [master]
    types: [opened,synchronize]

jobs: 

  avoid_reduncy:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previus Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{secrets.GIT_TOKEN}}

  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: extrayendo el repositorio
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '16'
      - name: npm install
        run: npm ci
      - name: lint
        run: npm run eslint
  
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: extrayendo el repositorio
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '16' 
      - name: npm install
        run: npm ci
      - name: build
        run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
      - name: Build fieled notification
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
            severity: error
            details: Build Failed!!!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  test:
    needs: [build, lint]
    runs-on: ubuntu-20.04
    steps:
      - name: extrayendo el repositorio
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '16' 
      - name: npm install
        run: npm ci
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: test
        run: npm run test
      - name: Test fieled notification
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
            severity: error
            details: Test Failed!!!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    
  test-e2e:
    needs: [build, lint]
    runs-on: ubuntu-20.04
    steps:
      - name: extrayendo el repositorio
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '16'
      - name: npm install
        run: npm ci
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: e2e tests
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Test fieled notification
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
            severity: error
            details: Test Failed!!!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  simple_deployment_pipeline:
    needs: [test,test-e2e]
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message,' '),'#skip')}}
    runs-on: ubuntu-20.04
    steps:
      - name: extrayendo el repositorio
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message,' '),'#skip') }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  new-deploy-notification:
    needs: simple_deployment_pipeline
    runs-on: ubuntu-20.04
    steps:
      - name: new deploy notification
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
            severity: info
            details: A new version of Pokedex deployed!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release:
    needs: [simple_deployment_pipeline]
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message,' '),'#skip')}}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: master