name: Deployment pipeline

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master
  pull_request:
    branches: [master]
    types: [opened,synchronize]

jobs: 

  npm-install:
    runs-on: ubuntu-20.04
    steps:
      - name: extrayendo el repositorio
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '16' 
      - name: npm install
        run: npm install

  lint:
    needs: npm-install
    runs-on: ubuntu-20.04
    steps:
      - name: extrayendo el repositorio
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install
        run: npm ci
      - name: lint
        run: npm run eslint
  
  build:
    needs: npm-install
    runs-on: ubuntu-20.04
    steps:
      - name: extrayendo el repositorio
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '16' 
      - name: npm install
        run: npm install
      - name: build
        run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
      

  test:
    needs: [build, lint]
    runs-on: ubuntu-20.04
    steps:
      - name: extrayendo el repositorio
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '16' 
      - name: npm install
        run: npm install
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: test
        run: npm run test
    
  test-e2e:
    needs: [build, lint]
    runs-on: ubuntu-20.04
    steps:
      - name: extrayendo el repositorio
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '16'
      - name: npm install
        run: npm install
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: e2e tests
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm run start-prod
          wait-on: http://localhost:5000
      

  simple_deployment_pipeline:
    needs: [test,test-e2e]
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message,' '),'#skip')}}
    runs-on: ubuntu-20.04
    steps:
      - name: extrayendo el repositorio
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message,' '),'#skip') }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  tag_release:
    needs: [simple_deployment_pipeline]
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message,' '),'#skip')}}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: master